"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import quote

import dj_database_url
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv()


def env_bool(name, default=False):
    """Read a boolean from the environment, accepting the usual spellings."""
    return os.getenv(name, str(default)).strip().lower() in ("1", "true", "yes", "on")


def env_list(name, default=""):
    """Read a comma-separated list from the environment, dropping blanks."""
    return [
        item.strip() for item in os.getenv(name, default).split(",") if item.strip()
    ]


# SECURITY WARNING: don't run with debug turned on in production!
# Defaults to False so that a missing DEBUG variable fails closed.
DEBUG = env_bool("DEBUG", False)

# SECURITY WARNING: keep the secret key used in production secret!
# There is deliberately no fallback in production: an unset SECRET_KEY must be
# a hard failure rather than a silently shared default.
SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "django-insecure-local-development-only-do-not-deploy"
    else:
        raise ImproperlyConfigured(
            "SECRET_KEY is not set. Generate one with:\n"
            '  python -c "from django.core.management.utils import '
            'get_random_secret_key; print(get_random_secret_key())"'
        )

ALLOWED_HOSTS = env_list(
    "ALLOWED_HOSTS", "localhost,127.0.0.1,yatrusathi-backend.onrender.com"
)

CSRF_TRUSTED_ORIGINS = env_list(
    "CSRF_TRUSTED_ORIGINS", "https://yatrusathi-backend.onrender.com"
)

# Security settings for Render's proxy
USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# HTTPS and cookie hardening — production only, so local http:// still works.
if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"


# Error tracking — no-op unless SENTRY_DSN is set (safe to leave unset in dev).
SENTRY_DSN = os.getenv("SENTRY_DSN", "").strip()
if SENTRY_DSN:
    import sentry_sdk

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=os.getenv("SENTRY_ENVIRONMENT", "production"),
        traces_sample_rate=float(os.getenv("SENTRY_TRACES_SAMPLE_RATE", "0.0")),
        send_default_pii=False,
    )


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "event",
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "django_filters",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # For static files in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "event.middleware.RequestLoggingMiddleware",  # Custom logging middleware
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database Configuration
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# PostgreSQL is the only supported engine — it is the data tier of the
# three-tier stack (React SPA -> Django API -> Postgres) and is the same
# engine everywhere: docker-compose runs the `db` service, Kubernetes points
# at managed RDS, and CI runs a Postgres service container.
#
# Configure it either way:
#   DATABASE_URL=postgres://user:pass@host:5432/dbname   (preferred; one DSN)
#   POSTGRES_HOST/POSTGRES_DB/POSTGRES_USER/POSTGRES_PASSWORD/POSTGRES_PORT
#
# There is deliberately no local-file fallback: a misconfigured database must
# fail loudly at startup rather than silently writing to throwaway storage.


def _database_url_from_parts():
    """Assemble a DSN from the discrete POSTGRES_* variables, or return ''."""
    host = os.getenv("POSTGRES_HOST", "").strip()
    if not host:
        return ""
    user = quote(os.getenv("POSTGRES_USER", "postgres"), safe="")
    password = quote(os.getenv("POSTGRES_PASSWORD", ""), safe="")
    port = os.getenv("POSTGRES_PORT", "5432").strip()
    name = os.getenv("POSTGRES_DB", "yatrusathi").strip()
    credentials = f"{user}:{password}@" if password else f"{user}@"
    return f"postgres://{credentials}{host}:{port}/{name}"


DATABASE_URL = os.getenv("DATABASE_URL", "").strip() or _database_url_from_parts()

if not DATABASE_URL:
    raise ImproperlyConfigured(
        "No database configured. YatruSathi requires PostgreSQL — set either\n"
        "  DATABASE_URL=postgres://user:password@host:5432/dbname\n"
        "or the discrete POSTGRES_HOST / POSTGRES_DB / POSTGRES_USER /\n"
        "POSTGRES_PASSWORD variables. For a local database, `docker compose up db`\n"
        "starts one and .env.example lists the matching values."
    )

DATABASES = {
    "default": dj_database_url.parse(
        DATABASE_URL,
        # Reuse connections across requests — establishing a Postgres
        # connection is expensive enough to matter per-request. Each Gunicorn
        # worker holds one, so watch the server's max_connections when
        # scaling replicas.
        conn_max_age=int(os.getenv("DB_CONN_MAX_AGE", "600")),
        conn_health_checks=True,
        ssl_require=env_bool("DB_SSL_REQUIRE", False),
    )
}

if DATABASES["default"].get("ENGINE") != "django.db.backends.postgresql":
    raise ImproperlyConfigured(
        "DATABASE_URL must point at PostgreSQL "
        f"(got engine {DATABASES['default'].get('ENGINE')!r})."
    )


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Media files (uploads)
# Use absolute URL in production if BACKEND_URL is provided
BACKEND_URL = os.getenv("BACKEND_URL", "").rstrip("/")
if BACKEND_URL:
    MEDIA_URL = f"{BACKEND_URL}/media/"
else:
    MEDIA_URL = "/media/"

MEDIA_ROOT = BASE_DIR / "media"

# CORS settings
# Origins are always an explicit allow-list. CORS_ALLOW_ALL_ORIGINS is never
# enabled, because CORS_ALLOW_CREDENTIALS makes a wildcard origin unsafe.
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = env_list(
    "CORS_ALLOWED_ORIGINS",
    ",".join(
        [
            "https://yartusathi-frontend.pages.dev",
            "https://yatrusathi-frontend.pages.dev",
            "http://localhost:5173",
            "http://localhost:3000",
            "http://127.0.0.1:5173",
            "http://127.0.0.1:3000",
        ]
    ),
)

# Email (Resend API preferred, SMTP fallback for local dev)
RESEND_API_KEY = os.getenv("RESEND_API_KEY")
RESEND_FROM_EMAIL = os.getenv("RESEND_FROM_EMAIL", "onboarding@resend.dev")

# Choose the backend explicitly with EMAIL_BACKEND; otherwise use real SMTP
# only when SMTP itself is configured, and fall back to printing emails to the
# console in local development.
#
# RESEND_API_KEY deliberately does NOT count here. Resend is called over its
# HTTP API (see event/services/auth_service.py), not SMTP, so treating the key
# as "SMTP is configured" pointed the fallback at smtp.gmail.com with no
# credentials — turning a recoverable Resend failure into a slow SMTP timeout
# and then a hard failure, instead of a visible console email.
# The console backend is a local-development convenience only. In production it
# would "accept" every message and drop it on stdout, so the OTP endpoints would
# report success for mail nobody receives — worse than a visible failure.
_smtp_configured = bool(os.getenv("EMAIL_HOST_PASSWORD"))
EMAIL_BACKEND = os.getenv(
    "EMAIL_BACKEND",
    (
        "django.core.mail.backends.smtp.EmailBackend"
        if _smtp_configured or not DEBUG
        else "django.core.mail.backends.console.EmailBackend"
    ),
)
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
# Bound the SMTP fallback. Without this an unreachable or unconfigured mail host
# blocks the request thread until the OS gives up.
EMAIL_TIMEOUT = int(os.getenv("EMAIL_TIMEOUT", "10"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@example.com"
)

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Allowed email domains for signup and login
ALLOWED_EMAIL_DOMAINS = ["gmail.com", "yahoo.com", "outlook.com", "hotmail.com"]

# REST Framework settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "event.authentication.AdminJWTAuthentication",
        "rest_framework.authentication.TokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ],
    "DEFAULT_PAGINATION_CLASS": "event.shared.pagination.StandardResultsSetPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.SearchFilter",
        "rest_framework.filters.OrderingFilter",
    ],
    "EXCEPTION_HANDLER": "event.shared.exceptions.api_exception_handler",
}

# Logging Configuration
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "[{levelname}] {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
        "simple": {
            "format": "[{levelname}] {message}",
            "style": "{",
        },
    },
    "filters": {
        "require_debug_true": {
            "()": "django.utils.log.RequireDebugTrue",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "level": "INFO",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": BASE_DIR / "logs" / "django.log",
            "maxBytes": 1024 * 1024 * 15,  # 15MB
            "backupCount": 10,
            "formatter": "verbose",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.db.backends": {
            "handlers": ["console"],
            "level": "DEBUG" if DEBUG else "INFO",
            "propagate": False,
        },
        "event": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}
