# Generated by Django 6.0.1 on 2026-01-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event_photos/'),
        ),
        migrations.DeleteModel(
            name='EventImage',
        ),
    ]
