# Generated by Django 6.0.1 on 2026-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_event_image_delete_eventimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
