# Generated by Django 6.0.1 on 2026-02-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gender_preference',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male Only'), ('female', 'Female Only')], default='any', max_length=20),
        ),
    ]
