# Generated by Django 6.0.1 on 2026-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_profile_kyc_status_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('citizenship', 'Citizenship'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('national_id', 'National ID')], max_length=50, null=True),
        ),
    ]
