# Generated by Django 6.0.1 on 2026-03-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_chatgroupreadstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='kyc_photo',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_photos/'),
        ),
    ]
