# Generated by Django 6.0.1 on 2026-03-26 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0020_profile_kyc_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_spouse_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='residential_status',
            field=models.CharField(blank=True, choices=[('resident', 'Resident Individual'), ('non_resident', 'Non Resident'), ('foreign_national', 'Foreign National')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='kyc_signatures/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('uid', 'UID (Aadhaar)'), ('passport', 'Passport'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
