# Generated by Django 6.0.1 on 2026-03-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0021_profile_date_of_birth_profile_father_spouse_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='document_type',
            field=models.CharField(blank=True, choices=[('nid', 'National ID (NID)'), ('passport', 'Passport'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
