apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yatrusathi

resources:
  - namespace.yaml
  - configmap.yaml
  - externalsecret.yaml
  - backend.yaml
  - frontend.yaml
  - chatbot.yaml
  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: yatrusathi
    includeSelectors: false
